### ISSUE TITLE
utf8 support

### ISSUE THREAD

**Issue by vladare** [thedod/feed2twister#10]
Hi,
Is it possible to add support for utf8 feeds?

**Comment by thedod** [comment]
Can you give an example of such a feed so that I can test the code with it?

**Comment by RealVegOs** [comment]
Perhaps "my" Japanese feed has that problem too. Feed address is http://japanfocus.org/admin/site_manage/rss/recent.rss - The feed contains kanjis.

**Comment by thedod** [comment]
It looks like utf-8 (not some exotic encoding), so theoretically it should work.
Don't know when I'll have time to test this (next month is kinda dense), but maybe you can paste the errors you're getting into some pastebin I'll get a clue about what's going wrong with that feed.

**Comment by RealVegOs** [comment]
I can paste that little output here:

blurp@blurper1:~$ /home/blurp/feed2twister/feed2twister.py -c /home/blurp/feed2twister-conf/japanfocus.conf
INFO:root:http://japanfocus.org/admin/site_manage/rss/recent.rss
Traceback (most recent call last):
  File "/home/blurp/feed2twister/feed2twister.py", line 180, in <module>
    main(n)
  File "/home/blurp/feed2twister/feed2twister.py", line 105, in main
    eid = '{0}|{1}'.format(feed_url,e.id)
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 424, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'id'

(Of course I'm not blurp and my computer is not blurper1) It works with other feeds. I tested with a shitty Twitter profile parsing feed.

**Comment by RealVegOs** [comment]
Sorry for opening again:
First line look good but still ends with attribute error:
(Same result after deleting the db file)

/home/blurb/feed2twister/feed2twister.py -c /home/blurb/feed2twister-conf/japanfocus.conf
INFO:root:http://japanfocus.org/admin/site_manage/rss/recent.rss
INFO:root:will post http://ur1.ca/nbikv 'Comfort Women' Denial and the Japanese Right
INFO:root:will post http://ur1.ca/nbikw âSomething Dreadful Happened in the Pastâs Local Peace Museums: The Conversion of Peace Osaka
INFO:root:will post http://ur1.ca/nbiky An â as Japanâs Grand Strategy: New Dynamism or Dead-End?
INFO:root:will post http://ur1.ca/nbikz To Whom Does the Sea Belong? Questions Posed by the Henoko Assessment
WARNING:root:Quota reached. Skipping 15 items:
Traceback (most recent call last):
  File "/home/blurb/feed2twister/feed2twister.py", line 183, in <module>
    main(n)
  File "/home/blurb/feed2twister/feed2twister.py", line 148, in main
    eeid = '{0}|{1}'.format(feed_url, ee.id)
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 424, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'id'

Perhaps a shitty RSS feed...

**Comment by thedod** [comment]
Reopening the ticket &mdash; @RealVegOs seems to still have issues with japanfocus

**Comment by thedod** [comment]
My mistake :confounded:
